server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comssa_app?serverTimezone=UTC&characterEncoding=UTF-8
#    url: jdbc:mysql://k7c204.p.ssafy.io:3306/S07P31C204?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&amp
    username: root
    password: thekey1919

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comssa

  profiles:
    include: oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  ## JWT Custom
  jwt:
    secret:
      signature: "Thekey"


  app:
    auth:
      tokenSecret: 926D96C90030DD58429D2751AC1BDBBC # JWT를 암호화 하기 위한 암호화 키
      tokenExpirationMsec: 864000000  # token 만료 기간 (24h * 60min * 60s * 1000ms)

    oauth2:
      # OAuth2 공급자로 성공적으로 인증 한 후 사용자에 대한 인증 토큰을 생성하고 토큰을
      # 프론트 엔드 클라이언트가 /oauth2/authorize 요청에서 지정한 redirectUri 입니다.
      # 쿠키는 모바일 클라이언트에서 잘 작동하지 않기 때문에 사용하지 않습니다
      authorizedRedirectUris:
        - http://localhost:8082/oauth2/redirect


    h2:
      console:
        enabled: true

