server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: comssa

    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: [ 9801ad08f8d5a556fa5aa7062582c327 ]
              redirect-uri: [ http://k7c204.p.ssafy.io ]
              authorization-grant-type: authorization_code
              client-authentication-method: POST
              client-name: Kakao
              scope:
                - profile_nickname
                - account_email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

## JWT Custom
jwt:
  secret:
    signature: "Thekey"