spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 'W7Jq18MlVPJQ0gdf_0oF'
            client-secret: nJ8y0WqCJp
            redirect-uri: 'http://localhost:8082/login/oauth2/code/naver' # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, nickname,profile_image
            client-name: Naver
          kakao:
            client-id: 9801ad08f8d5a556fa5aa7062582c327
            #redirect-uri: [ http://k7c204.p.ssafy.io ]
            redirect-uri: 'http://localhost:8082/kakao/callback'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id