server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comssa_app?serverTimezone=UTC&characterEncoding=UTF-8
#    url: jdbc:mysql://k7c204.p.ssafy.io:3306/S07P31C204?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&amp
    username: root
    password: thekey1919

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comssa

  profiles: oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
## JWT Custom
jwt:
  secret:
    signature: "Thekey"


app:
  auth:
    tokenSecret: secretkeyC204secretkeyC204secretkeyC204secretkeyC204secretkeyC204
    tokenExpiry: 204204204

